# Read the Docs 配置文件
version: 2

# 设置构建环境
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# 配置MkDocs
mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
  system_packages: true