[tool.poetry]
name = "lazyllm-rag"
version = "0.1.0"
description = ""
authors = ["sundebiao <sundebiao@sensetime.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
